spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/warehouse_erp?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.wk.servie.*
      # 配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  redis:
    jedis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: localhost
      # Redis服务器连接端口,默认6379
      port: 6379
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        # 连接池中的最大空闲连接
        max-idle: 300
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 0

  #关闭thymeleaf页面缓存
  thymeleaf:
    cache: false

  #开启热部署
  devtools:
    restart:
      enabled: true

  #设置上传文件大小,单位MB必须大写
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #统一设置后台返回到前台显示的格式以及时区 如果只要日期格式 在对应属性上加@JsonFormat(pattern = "yyyy-MM-dd")注解
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #设置前台传到后台数据的时间格式
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss


logging:
  level:
    com.wk.sys.mapper: trace
  pattern:
    console: "[%d{HH:mm:ss.SSS}] %-5p [%c] - %m%n"


#设置主键策略为数据库自增
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.wk.sys.entity
  mapper-locations: classpath:mapper/*/*.xml

#设置shiro
shiro:
  anon-urls:
    - /
    - /index.html
    - /toLogin
    - /login
    - /druid/**
    - /resources/**
  authc-urls:
    - /**
