spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shiro?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.wk.servie.*
      # 配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  redis:
    jedis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: localhost
      # Redis服务器连接端口,默认6379
      port: 6379
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        # 连接池中的最大空闲连接
        max-idle: 300
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 0
  #关闭thymeleaf页面缓存
  thymeleaf:
    cache: false
  #开启热部署
  devtools:
    restart:
      enabled: true

logging:
  level:
    com.wk.dao: trace
  pattern:
    console: "[%d{HH:mm:ss.SSS}] %-5p [%c] - %m%n"

#设置主键策略为数据库自增
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      #table-prefix: tb_    设置统一数据库表前缀
      #logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      #logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
    #除mp之外的自定义方法，其他配置和之前的mybatis一样
  type-aliases-package: com.wk.pojo
  mapper-locations: classpath:mappers/*.xml

